//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electronics_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentCode { get; set; }
        public Nullable<int> AccountCode { get; set; }
        public string ProductCode { get; set; }
        public string CommentContent { get; set; }
        public Nullable<System.DateTime> CommentTime { get; set; }
        public Nullable<double> Rate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Product Product { get; set; }
    }
}
