//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electronics_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImg
    {
        public int ProductImgCode { get; set; }
        public string Img { get; set; }
        public string ProductCode { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
